mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
  volumes:
    - "./mysgl-conf.d:/etc/mysql/conf.d:ro"
    - ./src/main/resources/db/mysql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    - ./src/main/resources/db/mysql/data.sql:/docker-entrypoint-initdb.d/2-data.sql

pet01:
  image: petim:staging
  
pet02:
  image: petim:staging

nginx:
  image: nginxim:staging
  ports:
    - "8080:80"

